[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
aegis_program = "8zA1db5LJmFwUu7dTS1qA4ixqJ5XaTx224x1fRTRSJHA"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[hooks]
